language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install: 
- ./install-sqc.sh
- pip install -r requirements.tx

install: python setup.py build install

script: pytest -v --runslow test/
