language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install: 
    - ./install-sqc.sh
    - pip install -r requirements.tx
    - export NUMPY_INCLUDE="-I$(python -c 'import numpy; print(numpy.get_include())')"
    - python -c 'import numpy; print(numpy.get_include())'

install: python setup.py build install

script: pytest -v --runslow test/
