language: python

python:
    #    - "3.6"
    #    - "3.7"
    - "3.8"

before_install: 
    - ./install-sqc.sh
    - pip install -r requirements.tx
    - export NUMPY_INCLUDE="-I$(python -c 'import numpy; print(numpy.get_include())')"
    - python -c 'import numpy; print(numpy.get_include())'
    - pip install codacy-coverage
    - pip install pytest-cov

install: python setup.py build install

script: 
    - pytest -v --cov=pyqcs --cov-report=xml --runslow test/
#    - python-codacy-coverage -r coverage.xml
