[project]
authors = [
    {name="Daniel Knüttel", email="daniel.knuettel@daknuett.eu"}
]

description = "A quantum computing simulator."
readme="README.rst"
requires-python=">=3.4"
platforms="linux"
home-page="https://github.com/daknuett/pyqcs"

[project.urls]
repository="https://github.com/daknuett/pyqcs"

[build-system]
requires = ["meson", "toml", "mesonpep517"]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
summary = "A quantum computing simulator"

