name: Build the package and upload it to PyPI
on: 
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: test package
        uses: ./.github/actions/test-tox-slow
      - name: run build
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: upload packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verify_metadata: true
            #- name: github release
            #  uses: softprops/action-gh-release@v1
            #  with:
            #    files: dist/*
